### ISSUE TITLE
[eCommerce Abandonment]: Debugger does not display on Safari browser

### ISSUE THREAD

**Issue by kamini1208** [mg2connext/connext#3]
the Debug Details does NOT display on any Safari browsers on any iOS device (iPhone, iPad and Mac).

**Comment by mg2dael** [comment]
Thanks, we've created a ticket for the problem. Can you let us know what version of the browser you were on so our QA can verify it?

**Comment by kamini1208** [comment]
On the Mac (Version 9.0.3), iPhone/iPad (10.1.1)

**Comment by kamini1208** [comment]
also, the presentation does not display as well.

**Comment by mg2dael** [comment]
We're having a hard time reproducing, though we don't have the exact devices you mentioned. We tried on a iPad on v10.0.1 and had no problems. Are you using an emulator or a physical device?

**Comment by mkoza178** [comment]
Dael,

Kamini is saying these are physical devices she is testing on.

**Comment by mg2dael** [comment]
Next troubleshooting question (I'm just going to keep using this bug instead of putting the same question in both): Are you looking at http://membercenter-staging.ajc.com/ or http://membercenter-dev-connext.aws.cmgdigital.com/newsletters?_tenant=ajc ? We're looking at the dev-connext when we're seeing it. The membercenter-staging doesn't have the connext instantiation so it wouldn't show anything there.

**Comment by kamini1208** [comment]
Hey Dael, I am verifying on this test mg2 URL that Gwen wanted me to take a look at: https://test-cox-paypanel-ajc.subscriberconcierge.com/subscriptionpanel.
I am seeing the debugger on the MC URLs - no prob there.

**Comment by mkoza178** [comment]
On https://test-cox-paypanel-ajc.subscriberconcierge.com/subscriptionpanel I am seeing the debugger as well on Safari. We okay to close?

**Comment by mkoza178** [comment]
Hey guys,

We okay to close this?

**Comment by kamini1208** [comment]
Closing issue.  Can view debugger on all Safari browsers.
