### ISSUE TITLE
[Targeted Messaging]: Incorrect Ad displaying for TM

### ISSUE THREAD

**Issue by kamini1208** [mg2connext/connext#8]
For Target Messaging, I am seeing the Ad for eCommerce Abandonment.  The Ad is a modal on the middle of the page instead of displaying under the Customer Service Box.  See Screen Shot: 
![screen shot 2016-12-13 at 10 38 35 am](https://cloud.githubusercontent.com/assets/20052632/21146729/b3cc7d56-c120-11e6-85fd-57fe26196e2e.png)

**Comment by mkoza178** [comment]
Hey Kamini, 

Can you send us the site you were on, the conversation you were testing and the debug details?

**Comment by gborders** [comment]
This was caused by a test modal that I placed in the Member Center conversation.  It has been removed

**Comment by kdakake** [comment]
Can we close this one?

**Comment by gborders** [comment]
yes

**Comment by lmai83** [comment]
Hey Everyone - Kamini and I are still experiencing pop-up ads on http://membercenter-dev-connext.aws.cmgdigital.com/edit-profile?_tenant=ajc

Here are two screenshots where I'm seeing ads:

![image](https://cloud.githubusercontent.com/assets/20074524/21190952/a8abfab0-c1f1-11e6-8fcf-b42d54c56335.png)

![image](https://cloud.githubusercontent.com/assets/20074524/21190977/bf34779e-c1f1-11e6-8c44-47f684d0ce96.png)

**Comment by mkoza178** [comment]
What is your expectation?

Also, we need to get you guys out of Dev. You should be testing against our Stage conneXt.

**Comment by mg2dael** [comment]
I'm guessing ConneXt stored cookies when you loaded it with the campaign that had a pop-up. If you click clear all data at the bottom of the debug panel http://i.prntscr.com/78731896bbe4490d914e80e6397bea56.png and then refresh your page it should clear out.

Marc is right that this sort of switching conversation is an issue of our testers trying to share an environment with your team. Natalia is trying to switch back once she's done testing, but ConneXt is designed to store data so that a user's information (such as article count) is retained. That clear on the debug should work whenever this happens, though.

**Comment by lmai83** [comment]
Thanks Dael, Marc - @sframe, our ticket to edit for these environments should fix this, maybe?

**Comment by kamini1208** [comment]
Closing this issue.  Not seeing experiencing the pop up ad anymore.

**Comment by sframe** [comment]
Hey @mkoza178 and @mg2dael, there's a lot of confusion (maybe just me) but is our "dev" instance supposed to now point to your "stage" environments? I was about to make the update to point to your "test" environment.

**Comment by mkoza178** [comment]
I believe your Dev points to our Test
Your Stage points to our Stage

Correct, Dael?
